//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMvcWebApp10pm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustId { get; set; }
        public string CustName { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> Age { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public Nullable<int> CreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
